In [10]:
import numpy as np

In [10]:
a= np.arange(2,15)

In [12]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
a[0]

2

In [16]:
a[::2]

array([ 2,  4,  6,  8, 10, 12, 14])

In [18]:
a[-1]

14

In [20]:
a = np.identity(8)

In [22]:
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
a[0]

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
a[1,1]

1.0

In [28]:
a[2,1]

0.0

In [30]:
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
a[2:5]

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [34]:
a[2:5,2:5]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
a[2:5,4]

array([0., 0., 1.])

In [38]:
a = np.arange(5,10)

In [40]:
a

array([5, 6, 7, 8, 9])

In [50]:
b = [True,True,False,True,False]

In [52]:
a[b]

array([5, 6, 8])

## create an arry of 5 of 5 of element 8 

In [75]:
a = np.full((5, 5), 8)

In [77]:
a

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [79]:
a[1:4,1:3]

array([[8, 8],
       [8, 8],
       [8, 8]])

### arithmetic operation on numpy array happens elementwise/indexwise

In [83]:
a= np.arange(2,10)

In [85]:
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a+2

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
a**2

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [91]:
salary = np.array([25000,34000,12000,13400])

In [93]:
salary-5000

array([20000, 29000,  7000,  8400])

In [95]:
a=np.array([1,2,3,4,5])
b=np.array([2,4,5,6,7])

In [97]:
a

array([1, 2, 3, 4, 5])

In [99]:
b

array([2, 4, 5, 6, 7])

In [101]:
a+b

array([ 3,  6,  8, 10, 12])

In [103]:
c= np.array([1,2,3])

In [105]:
c

array([1, 2, 3])

In [109]:
a

array([1, 2, 3, 4, 5])

In [111]:
a>3

array([False, False, False,  True,  True])

In [113]:
a%2 == 0

array([False,  True, False,  True, False])

In [115]:
a = np.arange(5,15)

In [117]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [119]:
(a%2 == 0)&(a > 8)

array([False, False, False, False, False,  True, False,  True, False,
        True])

In [121]:
a[b]

array([ 7,  9, 10, 11, 12])

In [123]:
a = np.arange(8)

In [125]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [127]:
a%2 == 0

array([ True, False,  True, False,  True, False,  True, False])

In [129]:
a[a%2 == 0]

array([0, 2, 4, 6])

In [131]:
a[(a%2==0) & (a>4)]

array([6])

In [18]:
a = np.arange(5,51)

In [20]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [24]:
a[(a%2 ==0)&(a%5==0)]

array([10, 20, 30, 40, 50])

In [149]:
a[(a%2 ==0) | (a%5==0)]

array([ 5,  6,  8, 10, 12, 14, 15, 16, 18, 20, 22, 24, 25, 26, 28, 30, 32,
       34, 35, 36, 38, 40, 42, 44, 45, 46, 48, 50])

In [12]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])