In [1]:
import numpy as np

## Declaration of array

### if datatype is not specified it will be in float

In [3]:
a = np.array([1,2,3,4])

## printing of array

In [5]:
a

array([1, 2, 3, 4])

In [7]:
b = np.array([[1,2,3],[4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

## This give dimension of array

In [11]:
b.ndim

2

In [13]:
a.ndim

1

## This gives size of array

In [15]:
a.size

4

In [17]:
b.size

6

## This gives number of rows and columns of array (row, columns). if it one dimensional it gives number of elements. It is written in tuple

In [19]:
b.shape

(2, 3)

In [21]:
a.shape

(4,)

## This gives datatype of Array

In [31]:
a.dtype

dtype('int32')

In [35]:
b.dtype

dtype('int32')

## This creates a random value Array

In [39]:
np.empty(3)

array([1.04918164e-153, 1.16096930e-028, 2.08961678e-076])

In [41]:
np.empty(3, dtype = 'int')

array([232460480,       459,         0])

In [43]:
np.empty((4,5))

array([[9.74131720e-312, 9.74146371e-312, 9.74146371e-312,
        9.74146371e-312, 9.74146371e-312],
       [9.74146371e-312, 9.74146371e-312, 9.74146370e-312,
        9.74146371e-312, 9.74146371e-312],
       [9.74146371e-312, 9.74146371e-312, 9.74146371e-312,
        9.74146371e-312, 9.74146371e-312],
       [9.74146371e-312, 9.74146371e-312, 9.74146371e-312,
        2.22522596e-306, 8.90029543e-307]])

## This creates an Identity matrix

In [48]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Creates an array full of ones

In [55]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [57]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## Creates an array full of Zero

In [64]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Creates an array of specific dimension and specified elements

In [71]:
np.full(4,5)

array([5, 5, 5, 5])

In [75]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

## This lines for doing sum, max , min , mean , varience, and standard deviation

In [87]:
a = np.array([1,2,3,4,5,6,7])

In [89]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
a.sum()

28

In [93]:
a.max()

7

In [95]:
a.min()

1

In [97]:
a.mean()

4.0

In [99]:
a.var()

4.0

In [101]:
a.std()

2.0

## sclicing

In [105]:
arr = np.array([1,2,3,4,5,6,7])

In [107]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

In [109]:
arr[1:]

array([2, 3, 4, 5, 6, 7])

In [111]:
arr[1:4]

array([2, 3, 4])

In [113]:
arr[::2]

array([1, 3, 5, 7])

In [116]:
arr[:-4]

array([1, 2, 3])