In [21]:
import numpy as np

## Declaration of array

In [25]:
a = np.array([1,2,3,4])

In [27]:
a

array([1, 2, 3, 4])

In [29]:
b = np.array ([1,2,3.0])

In [31]:
b

array([1., 2., 3.])

In [55]:
np.array([1.0,2.0,3.0],dtype ='int')

array([1, 2, 3])